language: python
sudo: false

env:
  - LUA="lua=5.1"

addons:
  apt:
    packages:
    - jq

cache:
  directories:
    - here
    - $HOME/.cache/pip

before_install:
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate

install:
  - luarocks show moonscript > /dev/null 2>&1 || luarocks install moonscript
  - luarocks show luacheck > /dev/null 2>&1 ||luarocks install luacheck
  - luarocks show busted > /dev/null 2>&1 ||luarocks install busted
  - curl -fsSLo release.sh https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
  - chmod +x release.sh

before_script:
  - moonc lint_config.moon
  - moonc -l .
  - luacheck . -q --codes --ranges

script:
  - busted

deploy:
  #- provider: script
  #  script: ./release.sh
  #- provider: script
  #  script: ./release.sh -s -p 0 -w 0
  - provider: script
    script: bash release.sh -g 1.13.2 -w 0
    skip_cleanup: true
  - provider: script
    script: bash release.sh -s -g 1.13.2 -p 0 -w 0
    skip_cleanup: true
